name = "blaze-intelligence-platform"
main = "src/index.ts"
compatibility_date = "2024-09-18"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "blazeintel.ai/*", zone_id = "YOUR_ZONE_ID" }
]

[vars]
CFB_API_KEY = "REPLACE_WITH_CFB_API_KEY"
ODDS_API_KEY = "REPLACE_WITH_ODDS_API_KEY"
ALLOWED_ORIGINS = "https://blazeintelligence.com,https://blaze-intelligence.netlify.app,https://blaze-3d.netlify.app"

# Environment configurations
[env.production]
name = "blaze-intelligence-platform"
vars = { ENVIRONMENT = "production", NODE_ENV = "production", VERSION = "1.0.0" }

[env.staging]
name = "blaze-intelligence-staging"
vars = { ENVIRONMENT = "staging", NODE_ENV = "staging", VERSION = "1.0.0-staging" }

# Storage configurations
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "blaze-platform-media"
preview_bucket_name = "blaze-platform-media-preview"

[[r2_buckets]]
binding = "MEDIA_STORAGE"
bucket_name = "blaze-intelligence-media"
preview_bucket_name = "blaze-intelligence-media-preview"

[[r2_buckets]]
binding = "DATA_STORAGE"
bucket_name = "blaze-intelligence-data"
preview_bucket_name = "blaze-intelligence-data-preview"

[[r2_buckets]]
binding = "YOUTH_DATA"
bucket_name = "blaze-youth-data"

# KV Namespaces
[[kv_namespaces]]
binding = "CACHE"
id = "kv-cache-production"
preview_id = "kv-cache-preview"

[[kv_namespaces]]
binding = "ANALYTICS_CACHE"
id = "analytics-cache-namespace"
preview_id = "analytics-cache-preview"

[[kv_namespaces]]
binding = "SPORTS_DATA" 
id = "sports-data-namespace"
preview_id = "sports-data-preview"

[[kv_namespaces]]
binding = "USER_SESSIONS"
id = "user-sessions-namespace"
preview_id = "user-sessions-preview"

[[kv_namespaces]]
binding = "KV"
id = "b884d8eb60454eed879d36c8863cf513"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "blaze-intelligence-edge"
database_id = "blaze-intelligence-edge-id"

[[d1_databases]]
binding = "BLAZE_DB"
database_name = "blaze-intelligence-db"
database_id = "blaze-intelligence-db-id"

[durable_objects]
bindings = [
  { name = "ScoreHub", class_name = "ScoreHub" }
]

[[queues.producers]]
binding = "INGEST"
queue = "ingest"

[[queues.consumers]]
queue = "ingest"
script_name = "blaze-intelligence-platform"

[triggers]
crons = [
  "0 2 * * *",      # Daily full ingestion at 2 AM CT
  "0 * * * *",      # Hourly priority updates
  "0 18 * * 0",     # Weekly Perfect Game sync
  "0 20 * * 3"      # Wednesday recruiting updates
]

[observability]
enabled = true

# Note: Multiple [triggers] sections merged above
# Monitoring and health checks are handled by the cron jobs defined earlier

