# Cloudflare Workers configuration for Biometric API
name = "biometric-api"
main = "api/biometrics.js"
compatibility_date = "2024-01-01"

[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"

[[r2_buckets]]
binding = "BIOMETRIC_DATA"
bucket_name = "blaze-biometric-data"

[build]
command = "echo 'Biometric API build complete'"