[build]
  command = "pnpm -r build --filter web"
  publish = "apps/web/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  path = "/coach/preview"
  function = "coach-preview"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/admin/*"
  to = "/login"
  status = 401

[dev]
  command = "pnpm dev --filter web"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "frame-ancestors 'self';"
