name = "blaze-intelligence"
compatibility_date = "2025-09-01"

[site]
bucket = "."
include = ["**/*"]
exclude = ["node_modules/**", ".git/**", "*.md", "logs/**", "cache/**"]

[[site.env.production.vars]]
ENVIRONMENT = "production"

[[site.env.staging.vars]]
ENVIRONMENT = "staging"

[build]
command = ""
cwd = ""
watch_dir = ""

[build.upload]
format = "service-worker"
