name = "blaze-intelligence-lsl"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[env.production]
name = "blaze-intelligence-production"

[[env.production.r2_buckets]]
binding = "BLAZE_STORAGE"
bucket_name = "blaze-intelligence-data"

# R2 Storage bindings
[[r2_buckets]]
binding = "BLAZE_STORAGE"
bucket_name = "blaze-intelligence-data"

# Pages Functions configuration handled automatically

# Environment variables for production
[env.production.vars]
API_VERSION = "1.0.0"
CACHE_TTL = "300"

# Production configuration will be handled via Cloudflare dashboard